_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 20
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('dior_trainval_all',)
  TEST: ('dior_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (10000, 13300) # (10000, 13300)
  MAX_ITER: 15000 # 15000
  CHECKPOINT_PERIOD: 200000
OUTPUT_DIR: "/Path/to/Output/Dir"